### ISSUE TITLE
Doesn't work with Newer SMB Wii 1.30

### ISSUE THREAD

**Issue by shamzam31** [Asu-chan/RiivolutionIsoBuilder#2]
Hello @Asu-chan, I'd like to thank you for your work as using Riivolution can be a bit of a pain. Unfortunately, I have found that the ISO builder doesn't work for the latest version of Newer Super Mario Wii. Picking an ISO or WBFS (that works normally), then the mod XML, produces a WBFS that unfortunately doesn't work even on Dolphin (!): after a few seconds after load, either on the safety screen or sideways wiimote prompt, Dolphin freezes and hangs after showing a "Stop current emulation? Y/N" prompt. Same with real hardware (Wii U in my case), where the console hard locks requiring to yank the power cable.

**Comment by shamzam31** [comment]
Update: other mods don't work either, eg. Mario's Final Adventure, whose README specifically says to use the builder (well, an earlier version/fork).

**Comment by Asu-chan** [comment]
Hey there.
Sorry to disappoint, but as said in the README:
> Please do NOT send me messages for support. If a mod doesn't work, it likely won't even with all my will put into it.

This tool is pretty much deprecated because:
* Dolphin now supports Riivolution patches, so you don't need to build a WBFS/ISO anymore.
* You can just use Riivolution on a real console (NSMBW discs are quite cheap and not so hard to find).

Still thanks for taking the time to open an issue, but I'll have to close it.
Have a nice day.
